using System;
using System.Runtime.InteropServices;
using Windows.Win32.Interop;

namespace Windows.Win32.Security
{
	[Flags]
	public enum CRED_FLAGS
	{
		CRED_FLAGS_PROMPT_NOW = 0x2,
		CRED_FLAGS_USERNAME_TARGET = 0x4
	}

	public enum CRED_TYPE
	{
		CRED_TYPE_GENERIC = 1,
		CRED_TYPE_DOMAIN_PASSWORD = 2,
		CRED_TYPE_DOMAIN_CERTIFICATE = 3,
		CRED_TYPE_DOMAIN_VISIBLE_PASSWORD = 4,
		CRED_TYPE_GENERIC_CERTIFICATE = 5,
		CRED_TYPE_DOMAIN_EXTENDED = 6,
		CRED_TYPE_MAXIMUM = 7,
		CRED_TYPE_MAXIMUM_EX = (CRED_TYPE_MAXIMUM + 1000)
	}

	public enum CRED_PERSIST
	{
		CRED_PERSIST_SESSION = 1,
		CRED_PERSIST_LOCAL_MACHINE = 2,
		CRED_PERSIST_ENTERPRISE = 3
	}
}